import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { useSelector } from 'react-redux'

import { Container } from '../components/Container'
import { UserItem } from '../components/UserItem'
import { useAppDispatch } from '../hooks/redux-hooks'
import { usersSelector } from '../selectors'
import { getAllUsers } from '../state/user-state'

const Home: NextPage = () => {
  const { users } = useSelector(usersSelector)

  const dispatch = useAppDispatch()

  useEffect(() => {
    dispatch(getAllUsers())
  }, [dispatch])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
        />
      </Head>
      <Container>
        {users?.map((user) => (
          <UserItem user={user} key={user.id} />
        ))}
      </Container>
    </div>
  )
}

export default Home
